name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      # 1. Python सेट करना (ताकि वर्जन की दिक्कत न आए)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 2. सभी जरूरी टूल्स डालना
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libffi-dev libssl-dev autoconf libtool openjdk-17-jdk unzip zip

      # 3. Buildozer डालना
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # 4. APK बनाना
      - name: Build APK
        run: |
          yes | buildozer android debug

      # 5. APK अपलोड करना
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Launcher-APK
          path: bin/*.apk
          
