name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 1. सेटअप (Setup)
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libffi-dev libssl-dev autoconf libtool openjdk-17-jdk
          python3 -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # 2. APK बनाना
      - name: Build APK
        run: |
          yes | buildozer android debug

      # 3. APK अपलोड करना
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Launcher-APK
          path: bin/*.apk
          
